dashboard/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("web.urls",namespace="web")),
    path("product/",include("product.urls",namespace="product")),
    path("user/",include("user.urls",namespace="user")),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

product/urls.py
from django.urls import path
from django.conf import settings
from product.views import category
from product.views import product
from product.views import addProduct,delProduct, editProduct, updateProduct, Product_view

app_name = "product"


urlpatterns = [
    path("",product,name="product"),
    path("category/",category,name="category"),
    path("addProduct/",addProduct, name="addProduct"),
    path('delProduct/<pk>',delProduct,name="delProduct"), 
    path('editProduct/<int:id>',editProduct,name="editProduct"), 
    path('updateProduct/<int:id>',updateProduct,name="updateProduct"), 
    path('delete/',Product_view.as_view(),name='delete')
]

user/urls.py
from django.urls import path
from django.conf import settings

from user.views import user_login, user_logout

app_name = 'user'

urlpatterns = [
    path("",user_login,name="user_login"), 
    path("user_logout",user_logout,name="user_logout") 
]

web/urls.py
from django.urls import path
from web.views import index

app_name = "web"

urlpatterns=[
    path("",index,name="index")
]

product/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import CharField


class Product(models.Model):
    product_name = models.CharField(max_length=255)
    unit_sold = models.IntegerField(null=True,blank=True)
    in_stock = models.IntegerField(null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    exp_date = models.DateField(null=True,blank=True)
    category = models.ForeignKey("product.Category",on_delete=models.CASCADE,null=True,blank=True)
    image = models.ImageField(upload_to="media/products",null=True,blank=True)
    
    def __str__(self):
        return self.product_name


class Category(models.Model):
    name = CharField(max_length=255)

    def __str__(self):
        return  self.name

user/models.py
from django.db import models
from django.db.models.fields import CharField


class Login(models.Model):
    username = models.CharField(max_length=255,blank=True,null=True)
    password = models.CharField(max_length=255,blank=True,null=True)
    
    def __str__(self):
        return self.username 
        

web/models.py
from django.db import models

# Create your models here.

product/forms.py
from django import forms
from django.db.models import fields
from django import forms
from django.forms import ModelForm, widgets
from django.forms.widgets import Select, TextInput, Textarea
from product.models import Product, Category
from django.forms.widgets import DateInput
from django.utils.translation import ugettext_lazy as _


class ProductForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    image = forms.ImageField()

    class Meta:
        model = Product
        exclude = ('unit_sold',)
        widgets = {
            "exp_date" : DateInput(attrs={'type': 'date'})
        }
        error_messages = {
            'product_name' : {
                'required' : _("product_name field is required."),
            },
            'in_stock' : {
                'required' : _("in_stock field is required."),
            },
            'description' : {
                'required' : _("description field is required."),
            },
            'exp_date' : {
                'required' : _("exp_date field is required."),
            },
            'category' : {
                'required' : _("category field is required."),
            },
            'category' : {
                'required' : _("category field is required."),
            },
            'image' : {
                'required' : _("image field is required."),
            },
        }
                

product/views.py
import json
from django.shortcuts import render,redirect
from django.http.response import JsonResponse
from product.models import Category, Product
from product.forms import ProductForm
from product.functions import generate_form_errors
from django.views.generic import View



def product(request):
    products=Product.objects.all()
    categories=Category.objects.all()
    context = {
        "products":products,
        "categories":categories
    }

    return render(request, "products.html",context=context)


def category(request):
    category_name =request.GET.get('category')
    if category_name:

        if category_name == "All":

            products = Product.objects.all().values()
            data = list(products)  
            response_data = {
                "title" : "success",
                "data" : data,
            }
        elif Category.objects.filter(name=category_name).exists():
            if Product.objects.filter(category__name=category_name).exists():
                products = Product.objects.filter(category__name=category_name).values()
                data = list(products)  

                response_data = {
                    "title" : "success",
                    "data" : data,
                }
            else:
                response_data = {
                    "title" : "failed",
                    "message" : "projects not found",
                }
        else:
            response_data = {
                "title" : "failed",
                "message" : "Category not found",
            }
    else:
        response_data = {
            "title" : "failed",
            "message" : "Category not found",
        }

    return JsonResponse({'response_data': response_data})
    


def addProduct(request):
    form = ProductForm(request.POST, request.FILES)
    print("=====================================",form.is_valid())
    if form.is_valid():
        form.save()
    return render(request,'add-product.html', {'form' : form})


def delProduct(request,pk):
    product = Product.objects.filter(pk=pk)
    product.delete()

    return redirect("product:product")

def editProduct(request,id):
    product=Product.objects.get(id=id)
    form = ProductForm(instance=product)
    return render(request,"edit-product.html",{ 'product':product,'form':form })


def updateProduct(request,id):
    product=Product.objects.get(id=id)
    form = ProductForm(request.POST, request.FILES, instance=product)

    context={
        "product" : product,
    }

    if form.is_valid():
        form.save()

        return redirect("product:product")
    else:
        print(generate_form_errors(form))

    return render(request,"edit-product.html", context = context)


class Product_view(View):
    def get(self,request):
        products=Product.objects.all()
        context ={
            "products":products,
        }
        return  render(request,"product.html", context=context)

    def post(self, request, *args, **kwargs):
        if request.method=="POST":
            product_ids=request.POST.getlist('id[]')
            for id in product_ids:
                product=Product.objects.get(pk=id)
                product.delete()
            return redirect("product:product")

user/views.py
from django.shortcuts import render, redirect
from product.models import Product
from user.models import Login
from django.contrib.auth import authenticate



def user_login(request):  
    if request.method == "POST":

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            request.session["username"] = username
            return  redirect("/")

    return render(request, "registration/login.html")


def user_logout(request):
    if "username" in request.session:
        del request.session["username"]
        
    return redirect('/') 

web/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from user.views import user_login

def index(request):
    if "username" in request.session:
        return render(request, "index.html")
    else:
        return redirect("user/")
   
        

templates/add-product.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Product - Dashboard Admin Template</title>
    <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-ui-datepicker/jquery-ui.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">
</head>

<body class="bg02">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-xl navbar-light bg-light">
                    <a class="navbar-brand" href="index.html">
                        <i class="fas fa-3x fa-tachometer-alt tm-site-icon"></i>
                        <h1 class="tm-site-title mb-0">Dashboard</h1>
                    </a>
                    <button class="navbar-toggler ml-auto mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="index.html">Dashboard
                                    <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="index.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    Reports
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Daily Report</a>
                                    <a class="dropdown-item" href="#">Weekly Report</a>
                                    <a class="dropdown-item" href="index.html">Yearly Report</a>
                                </div>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="products.html">Products</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="accounts.html">Accounts</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    Settings
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Profile</a>
                                    <a class="dropdown-item" href="#">Billing</a>
                                    <a class="dropdown-item" href="#">Customize</a>
                                </div>
                            </li>
                        </ul>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link d-flex" href="login.html">
                                    <i class="far fa-user mr-2 tm-logout-icon"></i>
                                    <span>Logout</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- row -->
        <div class="row tm-mt-big">
            <div class="col-xl-8 col-lg-10 col-md-12 col-sm-12">
                <div class="bg-white tm-block">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="tm-block-title d-inline-block">Add Product</h2>
                        </div>
                    </div>
                    <div class="row mt-4 tm-edit-product-row">
                        <div class="col-xl-7 col-lg-7 col-md-12">
                            <form action="{% url 'product:addProduct' %}" 
                                  class="tm-edit-product-form"
                                  method="POST"
                                  enctype="multipart/form-data">
                                  {% csrf_token %}
                                <div class="input-group mb-3">
                                    <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Product
                                        Name
                                    </label>
                                    <!-- <input id="name" name="name" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"> -->
                                    {{form.product_name}}
                                </div>
                                <div class="input-group mb-3">
                                    <label for="description" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 mb-2">Description</label>
                                    <!-- <textarea class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7" rows="3" required></textarea> -->
                                    {{form.description}}
                                </div>
                                <div class="input-group mb-3">
                                    <label for="category" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Category</label>
                                    <!-- <select class="custom-select col-xl-9 col-lg-8 col-md-8 col-sm-7" id="category">
                                        <option selected>Select one</option>
                                        <option value="1">Cras efficitur lacus</option>
                                        <option value="2">Pellentesque molestie</option>
                                        <option value="3">Sed feugiat nulla</option>
                                    </select> -->
                                    {{form.category}}
                                </div>
                                <div class="input-group mb-3">
                                    <label for="expire_date" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Expire
                                        Date
                                    </label>
                                    <!-- <input id="expire_date" name="expire_date" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"
                                        data-large-mode="true"> -->
                                        {{form.exp_date}}
                                </div>
                                <div class="input-group mb-3">
                                    <label for="stock" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Units In
                                        Stock
                                    </label>
                                    <!-- <input id="stock" name="stock" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-7 col-sm-7"> -->
                                    {{form.in_stock}}
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-12 mx-auto mb-4">
                                    <div class="tm-product-img-dummy mx-auto">
                                        <i class="fas fa-5x fa-cloud-upload-alt" onclick="document.getElementById('fileInput').click();"></i>
                                    </div>
                                    <div class="custom-file mt-3 mb-3">
                                        <input id="fileInput" type="file" style="display:none;" />
                                        {{form.image}}
                                        <!-- <input type="button" class="btn btn-primary d-block mx-auto" value="Upload ..." onclick="document.getElementById('fileInput').click();" -->
                                        
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="ml-auto col-xl-8 col-lg-8 col-md-8 col-sm-7 pl-0">
                                        <button type="submit" class="btn btn-primary">Add
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <footer class="row tm-mt-big">
            <div class="col-12 font-weight-light">
                <p class="d-inline-block tm-bg-black text-white py-2 px-4">
                    Copyright &copy; 2018 Admin Dashboard . Created by
                    <a rel="nofollow" href="https://www.tooplate.com" class="text-white tm-footer-link">Tooplate</a>
                </p>
            </div>
        </footer>
    </div>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'jquery-ui-datepicker/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
        $(function () {
            $('#expire_date').datepicker();
        });
    </script>
</body>

</html>

templates/edit-product.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Edit Product - Dashboard Template</title>
    <link
      rel="stylesheet"
      href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600' 5}"
    />
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'jquery-ui-datepicker/jquery-ui.min.css' %}"
      type="text/css"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}" />
  </head>

  <body class="bg02">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-xl navbar-light bg-light">
            <a class="navbar-brand" href="index.html">
              <i class="fas fa-3x fa-tachometer-alt tm-site-icon"></i>
              <h1 class="tm-site-title mb-0">Dashboard</h1>
            </a>
            <button
              class="navbar-toggler ml-auto mr-0"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                  <a class="nav-link" href="index.html"
                    >Dashboard
                    <span class="sr-only">(current)</span>
                  </a>
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="index.html"
                    id="navbarDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    Reports
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Daily Report</a>
                    <a class="dropdown-item" href="#">Weekly Report</a>
                    <a class="dropdown-item" href="index.html">Yearly Report</a>
                  </div>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="products.html">Products</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="accounts.html">Accounts</a>
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    Settings
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Billing</a>
                    <a class="dropdown-item" href="#">Customize</a>
                  </div>
                </li>
              </ul>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link d-flex" href="login.html">
                    <i class="far fa-user mr-2 tm-logout-icon"></i>
                    <span>Logout</span>
                  </a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
      <div class="row tm-mt-big">
        <div class="col-xl-8 col-lg-10 col-md-12 col-sm-12">
          <div class="bg-white tm-block">
            <div class="row">
              <div class="col-12">
                <h2 class="tm-block-title d-inline-block">Edit Product</h2>
              </div>
            </div>
            <div class="row mt-4 tm-edit-product-row">
              <div class="col-xl-7 col-lg-7 col-md-12">
                <form
                  action="{% url 'product:updateProduct' id=product.pk %}"
                  method="post"
                  class="tm-edit-product-form"
                  enctype="multipart/form-data"
                >
                  {% csrf_token %}
                  <div class="input-group mb-3">
                    <label
                      for="name"
                      class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label"
                      >Product Name
                    </label>
                    <!-- <input placeholder="Product name" value="In malesuada placerat" id="name" name="name" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"> -->
                    {{form.product_name}}
                  </div>
                  <div class="input-group mb-3">
                    <label
                      for="description"
                      class="col-xl-4 col-lg-4 col-md-4 col-sm-5 mb-2"
                      >Description</label
                    >
                    <!-- <textarea class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7" rows="3" placeholder="Product Description" required>Fusce finibus dui tellus, at viverra dui dignissim hendrerit. Sed a varius nulla. Donec auctor consectetur nulla.</textarea> -->
                    {{form.description}}
                  </div>
                  <div class="input-group mb-3">
                    <label
                      for="category"
                      class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label"
                      >Category</label
                    >
                    <!-- <select class="custom-select col-xl-9 col-lg-8 col-md-8 col-sm-7" id="category">
                                        <option value="1" selected>Cras efficitur lacus</option>
                                        <option value="2">Pellentesque molestie</option>
                                        <option value="3">Sed feugiat nulla</option>
                                    </select> -->
                    {{form.category}}
                  </div>
                  <div class="input-group mb-3">
                    <label
                      for="expire_date"
                      class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label"
                      >Expire Date
                    </label>
                    <!-- <input placeholder="Expire Date" value="2018-10-28" id="expire_date" name="expire_date" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7"
                                        data-large-mode="true"> -->
                    {{form.exp_date}}
                  </div>
                  <div class="input-group mb-3">
                    <label
                      for="stock"
                      class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label"
                      >Units In Stock
                    </label>
                    <!-- <input placeholder="Stock" value="255" id="stock" name="stock" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-7 col-sm-7"> -->
                    {{form.in_stock}}
                  </div>
                  <div class="custom-file mt-3 mb-3">
                    <!-- <input id="fileInput" type="file" style="display:none;" /> -->
                    {{form.image}}
                    <!-- <input type="button" class="btn btn-primary d-block mx-auto" value="Upload ..." onclick="document.getElementById('fileInput').click();"/> -->
                  </div>
                  <div class="input-group mb-3">
                    <div
                      class="ml-auto col-xl-8 col-lg-8 col-md-8 col-sm-7 pl-0"
                    >
                      <button type="submit" class="btn btn-primary">
                        Update
                      </button>
                    </div>
                  </div>
                  <div class="col-xl-4 col-lg-4 col-md-12 mx-auto mb-4">
                    <img
                      src="img/product-image.jpg"
                      alt="Profile Image"
                      class="img-fluid mx-auto d-block"
                    />
                    
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="row tm-mt-big">
        <div class="col-12 font-weight-light">
          <p class="d-inline-block tm-bg-black text-white py-2 px-4">
            Copyright &copy; 2018 Admin Dashboard . Created by
            <a
              rel="nofollow"
              href="https://www.tooplate.com"
              class="text-white tm-footer-link"
              >Tooplate</a
            >
          </p>
        </div>
      </footer>
    </div>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'jquery-ui-datepicker/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
      $(function () {
        $("#expire_date").datepicker();
      });
    </script>
  </body>
</html>